### ISSUE TITLE
Webinterface not working: Loading failed for the <script> with source “http://localhost:8989/maps/js/main.js?v=0.11.2”.

### ISSUE THREAD

**Issue by jolo2000** [geofabrik/OpenRailRouting#18]
Hi,

I installed and configured OpenRailRouting according to the readme file.
The call http://localhost:8989/ is routed to http://localhost:8989/maps/, but the display of the web form is incomplete.
The error of the web console is: "Loading failed for the <script> with source “http://localhost:8989/maps/js/main.js?v=0.11.2”."
But no file named "main.js" is to be found in the entire directory structure.
Any ideas, how to get the web interface to work?
<img width="1119" alt="Schnappschuss (2020-07-08 23 19 07)" src="https://user-images.githubusercontent.com/1190234/86971456-811f5180-c171-11ea-8112-0b8e3e8ccce1.png">

**Comment by jolo2000** [comment]
Solved:
In the directory /OpenRailRouting/graphhopper/web/src/main/resources/assets/js/
the file main.js is missing.

You can find the file main.js on the graphhopper github version 0.11, e.g.
./graphhopper-0.11.0/web/src/main/resources/assets/js/main.js

Grab this file main.js, add it to /OpenRailRouting/graphhopper/web/src/main/resources/assets/js/ and recompile OpenRailRouting with 
bash build.sh

HTH Johannes

**Comment by Nakaner** [comment]
Since GraphHopper 0.13 this file has not been part of the GraphHopper source code any more because it was generated using NodeJS (and it is not good practice to commit build artefacts to a source code repository). Instead of downloading the fil, you can generate it using the following command:

```sh
cd graphhopper/web && npm install && npm run bundleProduction && cd ../..
```

Source: https://github.com/graphhopper/graphhopper/blob/0.13.0/docs/core/quickstart-from-source.md

Starting with GraphHopper 1.0 or 1.1 (I don't know it by heart), npm is called by the Maven build process.

I will extend the build instructions for OpenRailRouting and have therefore reopened this ticket.

**Comment by jolo2000** [comment]
Thank you, for pointing out the usage of npm.
Now, it works like a charm.

BR Johannes

**Comment by Nakaner** [comment]
Javascript assets built is executed by Maven during normal build.
