### ISSUE TITLE
Map UI not working?

### ISSUE THREAD

**Issue by switschel** [geofabrik/OpenRailRouting#4]
Hi,

it seems that the Routing Map UI is not working. It just points to assets which contains a path where the UI is stored (graphhopper) but this is not going to work like this.
Is there a way how to make it work?

Regards
Stefan

**Comment by Nakaner** [comment]
Sorry, I have been serving the assets on my dev machine with Apache for a few weeks. It also acts as reverse proxy to Jetty/Dropwizard. That's why I did not notice that the assets are not working any more. I will have a look into it.

My production systems use the orignal GraphHopper web interface (logo and tile servers in `main.js` changed). Apache works as reverse proxy with a configuration similar to this:

```Apache
<VirtualHost *:443>
        DocumentRoot /var/www/routing-webinterface/
        ServerName mycool.hostname.tld
        ProxyPass /route http://127.0.0.1:8989/route
        ProxyPass /i18n http://127.0.0.1:8989/i18n
        ProxyPass /info http://127.0.0.1:8989/info
        ProxyPass /nearest http://127.0.0.1:8989/nearest
        ProxyPass /match http://127.0.0.1:8989/match
</VirtualHost>
```

https://github.com/Nakaner/graphhopper/tree/master/web/src/main/resources/assets is checked out at /var/www/routing-webinterface/

**Comment by Nakaner** [comment]
I just tested it and it works even without Apache by simply following the steps in the readme.
